name: release
on:
  push:
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Node & NPM
        uses: actions/setup-node@v3
      - name: Install node_modules
        run: npm install
      - name: Test & Coverage
        run: npm run test:coverage
      - name: Build
        run: npm run build
      - name: report coverage
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
